export const FETCH_CURRENT_WEATHER_DATA = "FETCH_CURRENT_WEATHER_DATA";
export const SET_CURRENT_WEATHER_DATA = "SET_CURRENT_WEATHER_DATA";

export const FETCH_FORECAST_WEATHER_DATA = "FETCH_FORECAST_WEATHER_DATA";
export const SET_FORECAST_WEATHER_DATA = "SET_FORECAST_WEATHER_DATA";

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
